name: Teste and Deploy

on:
  push:
    branches: [main, dev]


jobs:
  unitTest:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Get Code from repository
        uses: actions/checkout@v6
      - name: verifica se fez corretamente
        run:  ls -la
      - name: Instala o Node na maquina virtual
        uses: actions/setup-node@v3
      - name: Instala as dependencias do projeto
        run: npm ci
      - name: Roda os testes
        run: npm run test 
      - name: Gera relatorio de testes
        uses: dorny/test-reporter@v1
        if: success() || failure()  # roda de qualquer maneira
        with:
          name: JEST tests
          path: j*.xml
          reporter: jest-junit
          
