name: Teste and Deploy

on:
  push:
    branches: [main, dev]


jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.changes.outputs.api }}
      app: ${{ steps.changes.outputs.app }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            api:
              - 'api/**'
            app:
              - 'app/**'


  unitTestApi:
    needs: detect-changes
    if: needs.detect-changes.outputs.api == 'true'
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Get Code from repository
        uses: actions/checkout@v6
      - name: verifica se fez corretamente
        run:  ls -la
      - name: Instala o Node na maquina virtual        
        uses: actions/setup-node@v3
      - name: Instala as dependencias do projeto
        working-directory: api 
        run: npm ci
      - name: Roda os testes
        working-directory: api 
        run: npm run test 
      - name: verifica se fez corretamente
        working-directory: api 
        run:  ls -la        
      - name: Gera relatorio de testes
        uses: dorny/test-reporter@v1
        if: success() || failure()  # roda de qualquer maneira
        with:
          name: JEST tests
          path: ./api/j*.xml
          reporter: jest-junit
          
  deploy-api:
    needs: unitTestApi
    if: success()    
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Project 1
        run: |
          curl --fail --silent --show-error  \
            --request POST \
            --url https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID_1 }}/deploys \
            --header 'accept: application/json' \
            --header 'authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
            --header 'content-type: application/json' \
            -data '{"clearCache": "do_not_clear", "deployMode":"build_and_deploy"}'

